# Generated by Django 3.2.8 on 2021-11-01 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Turist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('content', models.TextField()),
                ('rasmi', models.CharField(max_length=400)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turist.category')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
